sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - BROWSERSTACK_USERNAME: anthonygubler1
  - BROWSERSTACK_ACCESS_KEY: hgyZkatVxo4WxGJLzmhq
install:
- travis_retry npm install grunt-cli
- travis_retry npm install
script:
- grunt
- grunt intern:node --combined
- grunt intern:browserstack --combined
- grunt remapIstanbul:ci
- grunt uploadCoverage
